### ISSUE TITLE
extend the documentation please

### ISSUE THREAD

**Issue by VanDerLars** [seatable/seatable-developer-docs#4]
This documentation is a joke. Please extend it, or remove the warning from the [old documentation](https://seatable.github.io/seatable-scripts/) that there's a new version.

(The old one wasn't perfect as well)

**Comment by freeplant** [comment]
What features do you think the new documentation is worse than the old one?

For example,  for the Python script documentation, do you think you need to put different categories of functions to its own page instead of a single page?

<img width="1256" alt="image" src="https://github.com/seatable/seatable-developer-docs/assets/109339/42f34c3b-bcc5-4250-b8d6-2cc55d5472b1">

Do you think the parameters of functions need to be explained in details?

**Comment by christophdb** [comment]
I close this issue due to missing information.
